"""ram status

Revision ID: c6afa7668ed2
Revises: 
Create Date: 2023-01-20 16:28:24.533361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6afa7668ed2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used', sa.Float(), nullable=True),
    sa.Column('free', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ram_status_id'), 'example_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ram_status_id'), table_name='example_responses')
    op.drop_table('example_responses')
    # ### end Alembic commands ###
